#!/bin/bash

# Manual Firestore Index Creation Guide
# This script provides the exact commands to create missing indexes

set -e

PROJECT_ID="careerrogue-4df28"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Firestore Index Creation Guide                    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "You need to create the following indexes manually:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "INDEX 1: tasks collection"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Collection: tasks"
echo "Fields:"
echo "  - session_id (Ascending)"
echo "  - status (Ascending)"
echo "  - updated_at (Descending)"
echo ""
echo "Click this link to create it:"
echo "https://console.firebase.google.com/v1/r/project/$PROJECT_ID/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9jYXJlZXJyb2d1ZS00ZGYyOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvdGFza3MvaW5kZXhlcy9fEAEaDgoKc2Vzc2lvbl9pZBABGgoKBnN0YXR1cxABGg4KCnVwZGF0ZWRfYXQQAhoMCghfX25hbWVfXxAC"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "INDEX 2: meetings collection"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Collection: meetings"
echo "Fields:"
echo "  - session_id (Ascending)"
echo "  - status (Ascending)"
echo "  - created_at (Ascending)"
echo ""
echo "Click this link to create it:"
echo "https://console.firebase.google.com/v1/r/project/$PROJECT_ID/firestore/indexes?create_composite=ClJwcm9qZWN0cy9jYXJlZXJyb2d1ZS00ZGYyOC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvbWVldGluZ3MvaW5kZXhlcy9fEAEaDgoKc2Vzc2lvbl9pZBABGgoKBnN0YXR1cxABGg4KCmNyZWF0ZWRfYXQQARoMCghfX25hbWVfXxAB"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEPS:"
echo "1. Click each link above (they will open in your browser)"
echo "2. Click 'Create Index' button"
echo "3. Wait 2-5 minutes for indexes to build"
echo "4. Check status at: https://console.firebase.google.com/project/$PROJECT_ID/firestore/indexes"
echo ""
echo "OR manually create them:"
echo "1. Go to: https://console.firebase.google.com/project/$PROJECT_ID/firestore/indexes"
echo "2. Click 'Create Index'"
echo "3. Enter the collection and fields as shown above"
echo "4. Click 'Create'"
echo ""
echo "After indexes are created, your 500 errors will be fixed!"
echo ""
